version: '3.9'

services:
    mysql:
        container_name: database
        image: mysql:8.0.28
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
        volumes:
            - ./mysql/init:/docker-entrypoint-initdb.d/
            - data:/var/lib/mysql/
        # DEBUG
        ports:
            - "3306:3306"
    redis:
        container_name: session-storage
        image: redis:6.2.7-alpine
        restart: unless-stopped
        command: redis-server --requirepass ${DATABASE_PASSWORD}
        volumes:
            - redis-data:/data/
        # DEBUG
        ports:
            - "6379:6379"
    website:
        container_name: Ticketing-system
        build: .
        restart: unless-stopped
        ports:
            - ${PORT}:3000
        environment:
            DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        volumes:
            - ./errors.log:/errors.log
volumes:
  data:
    driver: local
  redis-data:
    driver: local